{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "blogmap.serviceAccountName" . }}
  labels:
{{ include "blogmap.labels" . | nindent 4 }}
{{- end -}}
